name: casso
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: ^1.0.1
  lottie: ^1.2.1
  intl: ^0.17.0
  google_sign_in: ^5.2.3
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  get_storage: ^2.0.3
  cloud_firestore: ^3.1.8
  image_picker: ^0.8.5
  firebase_storage: 10.2.8
  flutter_image_compress: ^1.1.0
  flutter_slidable: ^1.2.0
  salomon_bottom_bar: ^3.3.0




  flutter: 
    sdk: flutter



dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter


flutter: 
  assets: 
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/products/
    
  fonts: 
    - family: Ubuntu
      fonts: 
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Light.ttf
          weight: 500
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 600
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700

    - family: balsamiq
      fonts: 
        - asset: fonts/BalsamiqSans-Regular.ttf
        - asset: fonts/BalsamiqSans-Bold.ttf
          weight: 800
    - family: mono
      fonts: 
        - asset: fonts/UbuntuMono-Bold.ttf
  uses-material-design: true

