name: casso
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: ^1.0.1
  lottie: ^1.2.1
  intl: ^0.17.0
  google_sign_in: ^5.2.3
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  get_storage: ^2.0.3
  cloud_firestore: ^3.1.8



  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Light.ttf
          weight: 500
        - asset: fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/Montserrat-Bold.ttf
          weight: 800



  uses-material-design: true